version: 2
updates:
  - package-ecosystem: "github-actions" # zizmor: ignore[dependabot-cooldown]
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: develop

  - package-ecosystem: "pip" # zizmor: ignore[dependabot-cooldown]
    directory: "/"
    file: "requirements_dev.txt"
    schedule:
      interval: "weekly"
    target-branch: develop
    groups:
      python-packages:
        patterns:
          - "*"