# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15my_grpc_service.proto\x12\x0fmy_grpc_service"\x19\n\tMyRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"\x1d\n\nMyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2P\n\tMyService\x12\x43\n\x08MyMethod\x12\x1a.my_grpc_service.MyRequest\x1a\x1b.my_grpc_service.MyResponseb\x06proto3',  # noqa: E501
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "my_grpc_service_pb2",
    _globals,
)
if not _descriptor._USE_C_DESCRIPTORS:  # noqa: SLF001
    DESCRIPTOR._loaded_options = None  # noqa: SLF001
    _globals["_MYREQUEST"]._serialized_start = 42  # noqa: SLF001
    _globals["_MYREQUEST"]._serialized_end = 67  # noqa: SLF001
    _globals["_MYRESPONSE"]._serialized_start = 69  # noqa: SLF001
    _globals["_MYRESPONSE"]._serialized_end = 98  # noqa: SLF001
    _globals["_MYSERVICE"]._serialized_start = 100  # noqa: SLF001
    _globals["_MYSERVICE"]._serialized_end = 180  # noqa: SLF001
# @@protoc_insertion_point(module_scope)
