# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\x07\x65xample\"!\n\x0eRequestMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0fResponseMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa0\x02\n\x0e\x45xampleService\x12?\n\nUnaryUnary\x12\x17.example.RequestMessage\x1a\x18.example.ResponseMessage\x12\x42\n\x0bUnaryStream\x12\x17.example.RequestMessage\x1a\x18.example.ResponseMessage0\x01\x12\x42\n\x0bStreamUnary\x12\x17.example.RequestMessage\x1a\x18.example.ResponseMessage(\x01\x12\x45\n\x0cStreamStream\x12\x17.example.RequestMessage\x1a\x18.example.ResponseMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTMESSAGE']._serialized_start=32
  _globals['_REQUESTMESSAGE']._serialized_end=65
  _globals['_RESPONSEMESSAGE']._serialized_start=67
  _globals['_RESPONSEMESSAGE']._serialized_end=101
  _globals['_EXAMPLESERVICE']._serialized_start=104
  _globals['_EXAMPLESERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
