extend = "../.ruff.toml"

[lint]
ignore = [
    "T201",   # many `print` in examples/
    "S104",   # in case of examples, this is not so critical
    "S311",   # `secrets` x1.75 slower that `random`
    "INP001",
    "SIM105", # `contextlib.suppress` x2 slower that `try-except-pass`
]

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
no-lines-before = ["local-folder"]

[lint.per-file-ignores]
"integrations/grpcio/pb2/**.py" = ["ALL"]
"integrations/grpcio/grpc_server.py" = ["N802"]
"real_world/tests/**.py" = [
    "ANN",
    "S101",
    "PLR2004",
]