[versions]
23121 = [
    "sanic==23.12.1",
    "sanic-testing==23.12.0",
    "setuptools==69.5.1",
    "-r", "requirements/asgi.txt",
]
2530 = [
    "sanic==25.3.0",
    "sanic-testing==24.6.0",
    "setuptools==70.1.0", # sanic==25.3.0 depends on setuptools>=70.1.0
    "-r", "requirements/asgi.txt",
]
latest = [
    "sanic",
    "sanic-testing",
    "setuptools>=69.5.1",
    "-r", "requirements/asgi.txt",
]
